-- Add menu items for July 2026 event
-- eventId: 1

INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('DR101', 'Durian Bubble Tea', 'DRINK', 10, 18, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('DR102', 'Creamy Matcha Bubble Tea', 'DRINK', 10, 20, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('DR103', 'ထိုင်း ရွှေရင်အေး', 'DRINK', 10, 17, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('DS101', 'Tiramisu', 'DESSERT', 15, 10, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('DS102', 'Matcha Chocolate Cookie', 'DESSERT', 10, 23, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('DS103', 'သာခွေယိုင်', 'DESSERT', 10, 21, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD101', 'အသုပ်စုံ', 'MAIN_DISH', 15, 20, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD102', 'နန်းကြီးသုပ်', 'MAIN_DISH', 15, 25, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD103', '၀က်သားတုတ်ထိုး', 'MAIN_DISH', 15, 19, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD104', 'ငါးကြော်နှပ်', 'MAIN_DISH', 20, 17, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD105', 'ငါးကြင်းဟင်း', 'MAIN_DISH', 20, 16, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD106', 'ဆိတ်ကလယ်ချက်', 'MAIN_DISH', 20, 21, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD107', 'ကြက်သားဒံပေါက်', 'MAIN_DISH', 20, 24, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD108', 'ပင်လယ်စာစုံချဉ်စပ်', 'MAIN_DISH', 20, 18, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD109', 'ပုဇွန်ချဉ်', 'MAIN_DISH', 15, 14, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD110', 'မြိတ်ပုဇွန်ချဉ်', 'MAIN_DISH', 15, 13, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD111', 'ပုဇွန်ခြောက် ဘလာချောင်ကြော်', 'MAIN_DISH', 15, 15, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD112', 'မရမ်းသီးငပိကြော်', 'MAIN_DISH', 15, 11, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD113', 'ငရုတ်သီးမှုန့်', 'MAIN_DISH', 10, 26, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD114', 'ကြက်သွန်ဖြူဆီချက်', 'MAIN_DISH', 10, 22, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD115', 'ချဉ်ပေါင်ကြော်', 'MAIN_DISH', 15, 20, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD116', 'သီးစုံသနပ်', 'MAIN_DISH', 15, 27, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD117', 'ရှမ်းတို့ဟူးကြော်', 'MAIN_DISH', 10, 23, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD118', 'ရှမ်းဟင်းထုပ် (၀က်)', 'MAIN_DISH', 15, 17, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD119', 'ဟင်းထုပ် (မာလ ကြက်)', 'MAIN_DISH', 15, 12, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD120', 'ကယားဝက်အူချောင်း', 'MAIN_DISH', 15, 18, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD121', 'ပဲကြော်', 'MAIN_DISH', 25, 10, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD122', 'ပဲပြုတ်', 'MAIN_DISH', 10, 20, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD123', 'ရှမ်းခေါက်ဆွဲ', 'MAIN_DISH', 20, 30, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD124', 'မုန့်ဟင်းခါး', 'MAIN_DISH', 15, 21, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('MD125', 'ကောက်ညှင်းပေါင်း', 'MAIN_DISH', 10, 24, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN101', 'မန္တလေး ပဲကြော်', 'SNACK', 10, 22, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN102', 'ကောက်ညှင်း ပဲကပ်ကြော်', 'SNACK', 10, 16, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN103', 'မုန့်လက်ကောက်', 'SNACK', 10, 19, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN104', 'ဒူးရင်းကောက်ညင်း', 'SNACK', 10, 15, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN105', 'မုန့်လုံးရေပေါ်', 'SNACK', 10, 18, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN106', 'ဇီးယို', 'SNACK', 10, 13, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN107', 'စာကလေးခွေ', 'SNACK', 10, 12, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN108', 'အုန်းနို့သာကူပြင်', 'SNACK', 10, 29, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN109', 'နို့မလိုင်လုံး', 'SNACK', 10, 17, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN110', 'ငှက်ပျောသီး ဆနွင်းမကင်း', 'SNACK', 10, 14, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN111', 'ရွှေကြည် ဆနွင်းမကင်း', 'SNACK', 10, 20, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN112', 'Nankahtai (နံကထိုင်)', 'SNACK', 10, 18, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN113', 'Chicken curry puff', 'SNACK', 15, 11, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN114', 'အာလူးမာလာ', 'SNACK', 10, 27, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SN115', 'မုန့်လေပွေ', 'SNACK', 10, 16, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SP101', 'မုန့်ဟင်းခါး Single Pack', 'MAIN_DISH', 15, 19, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SP102', 'မုန့်ဟင်းခါး Family Pack', 'MAIN_DISH', 50, 10, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SP103', '၀က်သားတုတ်ထိုး + ကြာဆံကြော် Single Pack', 'MAIN_DISH', 20, 14, 0, 1, NOW());
INSERT INTO menu_items (itemCode, name, category, price, stockQty, isSoldOut, eventId, createdAt) VALUES ('SP104', '၀က်သားတုတ်ထိုး + ကြာဆံကြော် Family Pack', 'MAIN_DISH', 50, 11, 0, 1, NOW());
